### ISSUE TITLE
SideBar - On the right

### ISSUE THREAD

**Issue by sumitdhameja** [creativetimofficial/material-dashboard-angular#18]
Hi, 
Thanks for your wonderful template. I need to create an additional toggle sidebar on the right side to add some filters. How do I go about doing it?

**Comment by alexandru-paduraru** [comment]
@sumitdhameja since the code that we implemented is working for only 1 sidebar. You have 2 options: 

1. write new code for the right sidebar and made the changes to the wrapper and main-panel in order for them to support the new sidebar
2. check this library: https://slideout.js.org/ and see if that helps in adding a right sidebar faster.

Hope this helps.

Best,
Alex
